# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FabbiAssigment' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FabbiAssigment
  pod 'R.swift'
  pod 'SwiftLint'
  target 'FabbiAssigmentTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FabbiAssigmentUITests' do
    # Pods for testing
  end

end
